### ISSUE TITLE
Support user edit travel mode

### ISSUE THREAD

**Issue by perfectly-preserved-pie** [zcutlip/pyonepassword#159]
https://developer.1password.com/docs/cli/reference/management-commands/user#user-edit

the `op` CLI can turn travel mode on or off: `op user edit <user> --travel-mode <on|off>`

Could you please add support for that? That's the one thing we'd love to be able to automate.

**Comment by zcutlip** [comment]
looks pretty straightforward. shouldn't be a problem

Please keep your usage scenarios in mind and how authentication would work for you.

Broadly speaking, there are four authentication scenarios:
- service accounts
- `op` connects to the desktop app to authenticate (usually with biometric)
- running `op signin` manually outside of the Python environment
- Passing a master password to `OP()`, which passes it to `op` over stdin

For most automation scenarios service accounts are preferred, but I believe they're not allowed to perform `op user edit` operations. So in this case you'd need to use one of the other available mechanisms, which may or may not be ideal for some automation tasks

**Comment by zcutlip** [comment]
I poked around on this a bit tonight with the Teams account for this project.

In theory this shouldn't be too hard to implement. I'l need to add:

- support for `op user edit`
- a `travel_mode=` kwarg

However, a minor fly in the ointment is this: Editing other users is a feature restricted to business accounts, which I don't have.

I have, however, discovered I can use `op user edit` on myself (e.g., `op signin --account <me>; op user edit <me>`) and it seems to work.

I won't be able to test this on arbitrary accounts however.

There have been a few things I've wondered how I'd implement, since they require business accounts, so I'll ask in the developers' slack for suggestions.

**Comment by zcutlip** [comment]
I have an implementation in the `dev/159-user-edit-travel-mode` branch that supports user editing

It supports setting travel mode on or off, as well as setting the user-visible name of a User object

I've lightly tested travel mode (with the caveat from above about not being able to test it on a different user than the one currently logged in). I've not tested changing the user's name attribute

@perfectly-preserved-pie if you're able to kick the tires on this branch I've love to hear your feedback

**Comment by zcutlip** [comment]
No worries! Whenever you get a chance. I still need to update `mock-op` for testing this and then add actual tests

**Comment by zcutlip** [comment]
Hmm another minor problem. At first blush I'm not sure how to add automated tests for this. The problem is there doesn't seem to be any way via `op` to verify whether travel mode has been successfully turned on (or off).

A couple weird things:
1. nothing about travel mode is appears in the output of `op user get` (JSON or otherwise)
2. And this is really weird, `op item get` appears to have access to all items, even those that should be restricted by travel mode

I'm able to visually verify that the restricted vaults do not appear in the apps when travel mode is turned on, but evidently this restriction does not apply to the `op` CLI command

I do have support added to `mock-op` both for recording `op` responses as well as for playing them back, fwiw. Just not sure what to observe about the user or their items in order to verify.

**Comment by zcutlip** [comment]
I have a question out about this in the developer slack. Waiting to hear back

**Comment by zcutlip** [comment]
anyway, I've added an automated test to enable/disable travel mode for a user, though it doesn't really test much:
https://github.com/zcutlip/pyonepassword/blob/da6957a5cbe2653aa381ceceda0968310841f2f1/tests/test_op_api/user/edit/test_user_edit_travel_mode.py

Still need to add a couple more tests:
- set a new username for a user (and set it back)
- perform a `user edit` operation on a non-existent user

**Comment by zcutlip** [comment]
The work is done and tests are added. Just need to merge

user-edit operations supported:

- travel mode
- new username

**Comment by zcutlip** [comment]
@perfectly-preserved-pie this is done as of release 4.2.0, and available in pypi. Let me know if you have any issues.

Release notes here:
https://github.com/zcutlip/pyonepassword/releases/tag/v4.2.0
