### ISSUE TITLE
Support for Service Accounts

### ISSUE THREAD

**Issue by tdb** [zcutlip/pyonepassword#38]
1Password is currently beta testing Service Accounts. From a CLI point of view, this is as simple as setting an environment variable and then proceeding as if you were already logged in. It'd be a great feature to have added.

Some more info can be found here:

https://developer.1password.com/docs/service-accounts/#step-2-use-a-service-account-with-1password-cli

**Comment by zcutlip** [comment]
Looks interesting, I'll take a look! Thanks for the heads up!

**Comment by zcutlip** [comment]
Ah it looks like I missed the beta sign-up window. I've inquired if its still possible to sign up [here](https://1password.community/discussion/comment/653427/#Comment_653427)

Otherwise, I may have to wait until it rolls out for everyone

**Comment by zcutlip** [comment]
Okay, got my service account access. This looks pretty straightforward.

@tdb How did you envision this working from a `pyonepassword` perspective?

Besides setting the environment variable outside of your python program or setting it yourself using `os.environ` before calling `pyonepassword` API, I could see:

- pass service account token as a kwarg to `OP()` constructor
- possibly a kwarg to subsequent operations, overriding the signed in account (I'd have to think about this as it breaks the current model)

Any other ideas?

**Comment by tdb** [comment]
I think just doing it via `OP()` is probably fine. Doing it with all subsequent operations to override is likely a bit of an edge case - how often is that likely to be needed?

It should support setting it externally so the token doesn't need to be set/known by the Python program though.

**Comment by zcutlip** [comment]
There are a few subtle issues I'll need to think through:
- What new failure states are there to handle and inform the caller about?
- How to communicate to `OP()`:
  - "use this service account key", vs
  - "I set a service account key environment variable for you, so rely on that"

Additionally, the set of kwargs to `OP()` is getting quite cluttered, and a little confusing. This will be due for an API-breaking refactor before too long (not a blocker for this feature request, just noting).

**Comment by zcutlip** [comment]
I've refactored OP() (technically `_OPCommandInterface()`) in PR #39 and deprecated a couple kwargs, replaced with new ones. Additionally the actual flow of authentication is cleaned up in support of adding new things such as service accounts.

In particular, `use_exisisting_session` has been deprecated in favor of `existing_auth`, which takes an enum that has three possible values (discussed below).

This replaces the idea of a session token, which is relevant specifically to password authentication with `op`, with the general idea of "I've already handled authentication for you in some way," whether that be:
- password sign-in with `eval $(op signin)`
- previously authenticated with TouchID (or whatever biometric is on non-macOS platforms)
- you've set OP_SERVICE_ACCOUNT_TOKEN
- or (hopefully) whatever comes next

The valid values for `existing_auth` are:
- `EXISTING_AUTH_IGNORE`: skip verification, and do normal authentication
- `EXISTING_AUTH_AVAIL`: try to verify existing authentication, and do normal authentication if that fails
- `EXISTING_AUTH_REQD`: verify existing authentication, and hard fail otherwise

Verification essentially consists of running `op whoami`, which will fail if there's no existing authentication, but importantly *does not* trigger a password or biometric prompt.

**Comment by zcutlip** [comment]
For now, a blocker is `op whoami` not working with service accounts. According to the 1Password community forum, this is planned.

Currently (as of 2.8.0-beta.03) `op whoami` fails, so it would be impossible to verify the service account is valid.

**Comment by zcutlip** [comment]
As of 2.8.0-beta.06 it appears `op whomi` works:
https://app-updates.agilebits.com/product_history/CLI2#v2080006 (click show betas)

This should be easy to finish.

**Comment by zcutlip** [comment]
Okay, this is what I'm working on now. stay tuned

**Comment by zcutlip** [comment]
Okay, preliminary support is working in the dev/support-service-accounts branch. Just set your `OP_SERVICE_ACCOUNT` environment variable ahead of time, either outside of python or using `os.environ`. 
Then pass either `EXISTING_AUTH_REQD` or `EXISTING_AUTH_AVAIL` to `OP()`.

**note**: you'll need to specify `vault=` either to the constructor or to individual queries, since service accounts require a vault to be specified.

Service account support in `op` is still evolving according to information I'm getting in slack. Namely there are a few things, I'm waiting on

- The dictionary returned from `op whoami` when using a service account hasn't been finalized. It's currently quite sparse, and also incompatible with the `whoami` dictionary for a proper user
- the token format, currently prefixed with `ops_` *may* change before final release
  - I'm hoping to add something like a `auth_token=` kwarg to `OP()` letting the caller pass in whatever token they want to use (session, svc acct, some future token type) 
  - In theory, I'd be able to parse that token to know what kind of authentication we're working with and give the caller meaningful feedback if things break
- It *sounds* as if there's going to be an `op service` command which I think may be useful in certain situations

**Comment by zcutlip** [comment]
Here's an example:
```python
from pyonepassword import OP
from pyonepassword.api.authentication import EXISTING_AUTH_REQD
from pyonepassword.api.exceptions import OPItemGetException
from pyonepassword.api.object_types import OPLoginItem
import os

os.env

def do_signin():
    # set OP_SERVICE_ACCOUNT_TOKEN env variable ahead of time,
    # and pass EXISTING_AUTH_REQD to ensure it gets used
    #
    # alternatively pass EXISTING_AUTHENTICATON_AVAIL
    # if no valid authentication exists (token expired, etc.)
    # you'll be prompted to authenticate interactively
    op = OP(existing_auth=EXISTING_AUTH_REQD)
    return op


def main():
    op = do_signin()

    try:
        item: OPLoginItem = op.item_get("Example Login 1", vault="Test Data")
        print(item.password)
    except OPItemGetException as e:
        print(e.err_output)
```

**Comment by zcutlip** [comment]
In addition to the checklist [here](https://github.com/zcutlip/pyonepassword/issues/38#issuecomment-1334260943), another thing that would make this feature more useful (as well as `pyonepassword` generally in a scripted environment) is a mode of operation that hard-fails if there is no valid authentication (no session, no service account token, etc).

This would ensure that a script running unattended doesn't trigger a prompt for authentication, either on the console, or via GUI (e.g., touch ID) and hang forever. Ideally an unattended script should hard-fail and log the error if authentication fails.

Here's my request for that feature
https://1password.community/discussion/comment/666122

**Comment by zcutlip** [comment]
service accounts are now in public beta, so I'm going to move forward on this. I don't think we can count the changes I was waiting for in the `op` command making it

**Comment by zcutlip** [comment]
I've got this working pretty well at the moment

The way it works is you set your `OP_SERVICE_ACCOUNT_TOKEN` environment variable before instantiating an `OP()` object, and you should be good to go.

`python-dotenv` is great for this, so you can have a `.env` (or whatever name you want to give it) file with secure permissions and is listed in your .gitignore

Your `existing_auth` preference will get upgraded to `EXISTING_AUTH_REQD` regardless what you pass in (or if you don't pass any value in), because if you have that environment variable set, even to something invalid or malformed, `op` ignores and won't prompt for any other authentication. So we won't try to authenticate any other way

**Comment by zcutlip** [comment]
what I'm working on at the moment is a filter to ensure any `op` operations that aren't compatible with service accounts, (or have required/prohibited options with service accounts) are flagged before executing the `op` command so we can raise an appropriate exception

the reason this is important is if we just run `op` and let it fail, it's hard to know _why_ it failed without scraping stderr. It could have failed because your service account token was revoked/malformed, or the item you were trying to get isn't there. So as much as possible I want to catch _guaranteed_ failures before they happen in order to raise a more precise exception, rather than just "command failed, here's it's error output, good luck"

**Comment by zcutlip** [comment]
sorry this took so long @tdb 

This should be complete as of version 3.10.0. Please give it a try and let me know if you have any problems!
