### ISSUE TITLE
No way to do initial sign-in on 1Password accounts with two-factor enabled

### ISSUE THREAD

**Issue by zcutlip** [zcutlip/pyonepassword#9]
When doing initial sign-in we send the password to `op` over stdin. But if the account has two-factor authentication enabled, then `op` will prompt for an authentication code. In this case, the user needs to have manually signed in before using `pyonepassword`.

I don't think there's any way to provide this to `op` programmatically, but if there was it would be nice to be able to do that.

**Comment by zcutlip** [comment]
May look at deprecating initial sign-in if it looks like there's no way forward to do this progamatically. I don't want this feature to help justify not turning of 2FA, and I'd rather remove initial sign-in that discourage anyone from turning on 2FA.

**Comment by acabey-klaviyo** [comment]
I've dug into this a bit for the last two days trying to work out a solution.

I am not exactly sure how, but for whatever reason I cannot get the op command to read the MFA code over stdin. With some static analysis of the binary and by looking at the file handles that the process `open`s during the sign-in process, the sequence goes:

1. Prompt for the password (i.e. print "Enter the password for <username> at <sign-in address>: ") on `/dev/tty`, rather than to `stdout`
2. Check if stdin isatty (`IsStdinFromTerminal()`). If not, then read "insecurely" from `stdin` (`ReadInsecurelyFromStdin()`), otherwise `ReadSecurelyFromTTY()`
3. If MFA is not enabled, print token to `stdout`. If MFA is enabled, prompt for the MFA token (i.e. "Enter your %s-digit MFA code: ") on `stderr` (not sure why they would do this...)
4. Read "insecurely" from `stdin` (`ReadInsecurelyFromStdin()`)
5. If successful, print token to `stdout` 

I tried various approaches using subprocess and pipes along these lines

```
        # Create process
        proc = subprocess.Popen(argv, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

        # Password prompt goes to /dev/tty
        
        # Write password
        written = proc.stdin.write(password + b'\n')
        
        # Check for MFA prompt or token
        prompt = proc.stderr.read()
        
        # Write MFA code
        proc.stdin.write((mfa_code + b'\n'))
        
        # Check for token
        print(proc.stdout.read())
```

but no matter what variations I tried I could not get any output back, and seemingly could not get `op` to read my input.

I have, however, gotten a proof of concept to work by using a pseudo-tty (ptty). The code below is a pretty hacky solution, and has a race condition in the `read` calls where, unless you are step-debugging, the `read` will typically produce either an empty or truncated string. I tried this same approach using `select` to check if the fd is has data to read from, but it suffered from the same race condition.

If you do step-debug through the code and presumably allow time for the kernel pty buffers to fill before reading, you can successfully get the token back from `op` with MFA enabled. At the very least, this proves that MFA can be supported programmatically, but I need to play around more with this pty to get it to work properly

```
    @classmethod
    def _run_signin(cls, argv, password=None, mfa_code=None):

        if password:
            if isinstance(password, str):
                password = password.encode("utf-8")
        else:
            raise ValueError("Cannot run signin with empty password")

        if mfa_code:
            if isinstance(mfa_code, str):
                mfa_code = mfa_code.encode("utf-8")

        try:
            # Create psuedo TTY to bypass isatty checks
            inp = pty.openpty()
            # Launch process with ptty
            proc = subprocess.Popen(argv, stdin=inp[1], stdout=inp[1], stderr=inp[1])

        except FileNotFoundError as err:
            cls.logger.error(
                "1Password 'op' command not found at: {}".format(argv[0]))
            cls.logger.error(
                "See https://support.1password.com/command-line-getting-started/ for more information,")
            cls.logger.error(
                "or install from Homebrew with: 'brew install 1password-cli")
            raise OPNotFoundException(argv[0], err.errno) from err

        try:

            # Read password prompt
            prompt = os.read(inp[0], 1024).decode("utf-8")

            if "ERROR" in prompt:
                proc.terminate()
                raise OPSigninException(f'Error on signin: {prompt}', proc.returncode)
            elif "Enter the password" not in prompt:
                proc.terminate()
                raise OPSigninException(f'Unexpected signin output: {prompt}', proc.returncode)
            elif prompt == '':
                proc.terminate()
                raise OPSigninException(f'Expected password prompt', proc.returncode)

            # Write password
            written = os.write(inp[0], password + b'\n')

            if written < len(password + b'\n'):
                proc.terminate()
                raise OPSigninException(f'Failed to write password', proc.returncode)

            # Check for MFA prompt or token
            prompt = os.read(inp[0], 1024).decode("utf-8")

            # Check for errors (e.g. incorrect password)
            if "ERROR" in prompt:
                proc.terminate()
                raise OPSigninException(f'Unexpected signin output: {prompt}', proc.returncode)

            elif prompt == '':
                proc.terminate()
                raise OPSigninException(f'Expected either MFA prompt or token', proc.returncode)

            # Check for MFA prompt
            elif "Enter your six-digit" in prompt:

                # Write MFA code
                written = os.write(inp[0], mfa_code + b'\n')
                if written < len(mfa_code + b'\n'):
                    proc.terminate()
                    raise OPSigninException(f'Failed to write MFA code', proc.returncode)

                # Check for token
                token = os.read(inp[0], 1024).decode("utf-8")

                if "ERROR" in token:
                    proc.terminate()
                    raise OPSigninException(f'Error on token output: {prompt}', proc.returncode)

                elif token == '':
                    proc.terminate()
                    raise OPSigninException(f'Expected token', proc.returncode)

                # Successfully authenticated with MFA. Output is token
                # 6 digit MFA code followed by \r\n is prepended to token, must be stripped
                return token[8:].strip()

            # MFA is disabled, output is token
            else:
                return prompt.strip()

        except (KeyboardInterrupt, OPCmdFailedException) as e:
            raise OPSigninException('Unexpected error', proc.returncode) from e

```

**Comment by zcutlip** [comment]
Oh wow, you've put a lot of work into this.

A couple thoughts: 

- This approach is a bit screen-scrapey, which could be brittle if `op` changes its output
- As much as possible I'd like to keep this OS-agnostic, because I think some people are using it on windows. is pty stuff portable? Honestly don't know

I'll keep an eye out to see what you come up with. Although initial sign-in/mfa support isn't super important to me personally, I can understand others wanting/needing it. I don't mind adding it if it's secure, maintainable, and reliable.

**Comment by acabey-klaviyo** [comment]
Screen-scrapey is a good way to put it as the pty is effectively multiplexing stdin, stdout, stderr, and /dev/tty into one bidirectional channel; with this approach you do lose out on granularity and run into these timing issues. Unless I can figure out non timing-based cues on when to do the read() and write() calls, the pty method is definitely brittle.

Availability wise, the pseudo tty relies on [os.openpty](https://docs.python.org/3/library/os.html#os.openpty), which to my knowledge is not available on Windows.

I will take another shot with the pipes approach and see if I can't figure out how to make OP to split up the password and MFA code.

**Comment by zcutlip** [comment]
This is officially deprecated as of v2.0 (e4d32bd8a157e20f2369259cbfbc81e2d3309986). Closing this issue
